force-app/main/default/objects/Coverage_Area__c/Coverage_Area__c.object-meta.xml
<CustomObject>
    <label>Coverage Area</label>
    <nameField>
        <displayFormat>COV-{0000}</displayFormat>
        <label>Coverage Area Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coverage Areas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Coverage_Area__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <description>Código de Endereçamento Postal</description>
    <externalId>true</externalId>
    <label>CEP</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Coverage_Area__c/fields/Has_Fiber_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Has_Fiber_Coverage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Define se o CEP tem fibra ótica</description>
    <label>Has Fiber Coverage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Coverage_Area__c/fields/Max_Speed_Available__c.field-meta.xml
<CustomField>
    <fullName>Max_Speed_Available__c</fullName>
    <description>Velocidade máxima disponível</description>
    <label>Max Speed Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>300 Mbps</fullName>
            </value>
            <value>
                <fullName>600 Mbps</fullName>
            </value>
            <value>
                <fullName>1 Gbps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConnectMaxCoverageAPI.cls
@RestResource(urlMapping='/api/v1/coverageCheck/*')
global with sharing class ConnectMaxCoverageAPI {
    global class CoverageResponse {
        global Boolean success { get; set; }
        global String message { get; set; }
        global String cepConsulta { get; set; }
        global Boolean hasCoverage { get; set; }
        global String maxSpeed { get; set; }

        global CoverageResponse(Boolean success, String message, String cep, Boolean coverage, String speed) {
            this.success = success;
            this.message = message;
            this.cepConsulta = cep;
            this.hasCoverage = coverage;
            this.maxSpeed = speed;
        }
    }

    @HttpGet
    global static void checkCoverage() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        CoverageResponse responseBody;

        String cep = '';

        try {
            cep = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
            List<Coverage_Area__c> coverageList = [ 
                SELECT Has_Fiber_Coverage__c, Max_Speed_Available__c 
                FROM Coverage_Area__c
                WHERE CEP__c = :cep
                LIMIT 1
            ];

            if(!coverageList.isEmpty()) {
                Coverage_Area__c area = coverageList[0];
                responseBody = new CoverageResponse(
                    true,
                    'Consulta realizada com sucesso',
                    cep,
                    area.Has_Fiber_Coverage__c,
                    area.Max_Speed_Available__c
                );

                res.statusCode = 200;
            } else {
                responseBody = new CoverageResponse(
                        true, 
                        'Região não atendida pela ConnectMax.', 
                        cep, 
                        false, 
                        null
                    );
                    res.statusCode = 200;
            }
        } catch (Exception e) {
            responseBody = new CoverageResponse(
                false,
                'Erro interno no servidor ' + e.getMessage(),
                cep,
                false,
                null
            );
            res.statusCode = 500;
        }

        res.addHeader('Content-Type', 'application/json');
        res.responseBody = Blob.valueOf(JSON.serialize(responseBody));
    }
}